# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0rdW_OA2bq8jkz1_gqTZikb6GhQT7-k
"""

import pandas as pd
df = pd.DataFrame({ 'Ism': [ 'Zulayho', 'Nigora'    ],
                   'Familiya':[ 'Qadamova','Yusupova'     ],
                    'Yoshi': [ '28' ,'17'     ],
                    'Kursi':[ '4', '2'    ]

})
print(df)

df.to_excel('guruh.xlsx', index=False, sheet_name='Sheet1')

